insert into Products (Name, UnitCost) values ('Lidocaine Hydrochloride and Epinephrine', 603.12);
insert into Products (Name, UnitCost) values ('Petrolatum', 1982.76);
insert into Products (Name, UnitCost) values ('red bell pepper', 1183.1);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 1803.49);
insert into Products (Name, UnitCost) values ('Olanzapine', 505.16);
insert into Products (Name, UnitCost) values ('Aspergillus flavus', 1727.22);
insert into Products (Name, UnitCost) values ('Enoxaparin sodium', 1232.04);
insert into Products (Name, UnitCost) values ('Levothyroxine Sodium', 1023.88);
insert into Products (Name, UnitCost) values ('Imipramine Pamoate', 1520.74);
insert into Products (Name, UnitCost) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 280.79);
insert into Products (Name, UnitCost) values ('METHYL SALICYLATE', 1195.72);
insert into Products (Name, UnitCost) values ('Salicylic Acid', 1236.94);
insert into Products (Name, UnitCost) values ('MANNITOL', 2.07);
insert into Products (Name, UnitCost) values ('Ramipril', 952.82);
insert into Products (Name, UnitCost) values ('Isuprel', 497.15);
insert into Products (Name, UnitCost) values ('Zinc Oxide', 547.59);
insert into Products (Name, UnitCost) values ('Titanium dioxide', 1272.82);
insert into Products (Name, UnitCost) values ('Acetaminophen', 181.38);
insert into Products (Name, UnitCost) values ('Fluoride Toothpaste', 700.25);
insert into Products (Name, UnitCost) values ('Ranitidine', 696.73);
insert into Products (Name, UnitCost) values ('Oxcarbazepine', 1964.32);
insert into Products (Name, UnitCost) values ('Eucalyptol', 1192.47);
insert into Products (Name, UnitCost) values ('Zinc Oxide and Titanium Dioxide', 536.49);
insert into Products (Name, UnitCost) values ('Ethyl Alcohol', 1083.41);
insert into Products (Name, UnitCost) values ('CLADOSPORIUM SPHAEROSPERMUM', 1898.22);
insert into Products (Name, UnitCost) values ('Hydrocortisone', 628.11);
insert into Products (Name, UnitCost) values ('Foscarnet Sodium', 153.58);
insert into Products (Name, UnitCost) values ('sodium fluoride', 1880.25);
insert into Products (Name, UnitCost) values ('Selenium Sulfide', 168.11);
insert into Products (Name, UnitCost) values ('Triamterene and Hydrochlorothiazide', 1564.36);
insert into Products (Name, UnitCost) values ('Ceftriaxone Sodium', 690.0);
insert into Products (Name, UnitCost) values ('Coal Tar', 1563.23);
insert into Products (Name, UnitCost) values ('Sodium Bicarbonate', 617.13);
insert into Products (Name, UnitCost) values ('moxifloxacin hydrochloride', 108.9);
insert into Products (Name, UnitCost) values ('lidocaine HCl', 1512.61);
insert into Products (Name, UnitCost) values ('HYOSCYAMINE SULFATE', 627.8);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 108.28);
insert into Products (Name, UnitCost) values ('Adrenal, Amoeba nosodes, Artemisia absinthium', 476.9);
insert into Products (Name, UnitCost) values ('Goldenrod, Red clover, Alfalfa, Sheep sorrel, Yellow dock, Kentucky bluegrass, Orchard grass, Redtop grass, Timothy grass, Giant ragweed, False ragweed, Short ragweed,', 1344.36);
insert into Products (Name, UnitCost) values ('Menthol', 372.98);
insert into Products (Name, UnitCost) values ('Dextromethorphan HBr. and Guaifenesin', 1342.48);
insert into Products (Name, UnitCost) values ('Penicillin V Potassium', 699.1);
insert into Products (Name, UnitCost) values ('Apis, Berberis Vulgaris, Bryonia, Cantharis, Staphysaria, Sarsaparilla, Urtica Urens', 1805.73);
insert into Products (Name, UnitCost) values ('Citalopram Hydrobromide', 1910.38);
insert into Products (Name, UnitCost) values ('Topiramate', 587.55);
insert into Products (Name, UnitCost) values ('Boletus luridus, Bryonia, Crotalus horridus, Echinacea purpurea, Gelsemium sempervirens, Gentiana lutea, Kali phosphoricum, Lachesis mutus, Mercurius vivus, Muriaticum acidum, Natrum sulphuricum, Nitricum acidum, Phosphoricum acidum, Veratrum album', 901.9);
insert into Products (Name, UnitCost) values ('Titanium Dioxide and Zinc Oxide', 982.17);
insert into Products (Name, UnitCost) values ('Aurum Stibium Special Order', 1543.92);
insert into Products (Name, UnitCost) values ('calcium carbonate', 1115.57);
insert into Products (Name, UnitCost) values ('Nadolol', 1120.94);
insert into Products (Name, UnitCost) values ('Bisacodyl', 1407.38);
insert into Products (Name, UnitCost) values ('Aluminum Chloride', 1845.0);
insert into Products (Name, UnitCost) values ('Carbidopa and levodopa', 1470.89);
insert into Products (Name, UnitCost) values ('Carya illinoinensis', 927.0);
insert into Products (Name, UnitCost) values ('furosemide', 1736.37);
insert into Products (Name, UnitCost) values ('Salt Grass', 452.34);
insert into Products (Name, UnitCost) values ('Dexamethasone', 629.63);
insert into Products (Name, UnitCost) values ('Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate, and Amphetamine Sulfate', 355.69);
insert into Products (Name, UnitCost) values ('clobetasol propionate', 923.72);
insert into Products (Name, UnitCost) values ('Dimethicone, Octinoxate, Octisalate, Oxybenzone', 527.9);
insert into Products (Name, UnitCost) values ('AMMONIUM CARBONATE - APIS MELLIFERA - ARSENIC TRIOXIDE - BLATTA ORIENTALIS - CUPRIC ACETATE - DRIMIA MARITIMA BULB - EPINEPHRINE - GALPHIMIA GLAUCA FLOWERING TOP - HISTAMINE DIHYDROCHLORIDE - LUFFA OP', 1199.83);
insert into Products (Name, UnitCost) values ('Chloroxylenol', 1427.55);
insert into Products (Name, UnitCost) values ('Betaxolol', 1952.24);
insert into Products (Name, UnitCost) values ('OCTINOXATE and TITANIUM DIOXIDE', 812.72);
insert into Products (Name, UnitCost) values ('Mineral Oil', 1191.74);
insert into Products (Name, UnitCost) values ('Ethyl Alcohol', 934.39);
insert into Products (Name, UnitCost) values ('Pyrithione Zinc', 386.87);
insert into Products (Name, UnitCost) values ('Acetaminophen, Aspirin, Caffeine', 1779.05);
insert into Products (Name, UnitCost) values ('Nicotine polacrilex', 863.45);
insert into Products (Name, UnitCost) values ('Ibuprofen', 81.25);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 1011.41);
insert into Products (Name, UnitCost) values ('Tree Mix 6', 219.56);
insert into Products (Name, UnitCost) values ('Fenofibrate', 536.46);
insert into Products (Name, UnitCost) values ('Cetirizine HCl', 1068.55);
insert into Products (Name, UnitCost) values ('Glycerin', 653.08);
insert into Products (Name, UnitCost) values ('Acetaminophen, Guaifenesin, Phenylephrine HCl', 944.14);
insert into Products (Name, UnitCost) values ('Elm, American Ulmus americana', 56.81);
insert into Products (Name, UnitCost) values ('Eucalyptol, menthol, Methyl salicylate, thymol', 418.33);
insert into Products (Name, UnitCost) values ('Calc Phos', 1839.78);
insert into Products (Name, UnitCost) values ('Robinia Nicotiana', 478.24);
insert into Products (Name, UnitCost) values ('niacinamide', 83.01);
insert into Products (Name, UnitCost) values ('Atenolol', 437.25);
insert into Products (Name, UnitCost) values ('cyclobenzaprine hydrochloride', 806.99);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1813.53);
insert into Products (Name, UnitCost) values ('Sertraline Hydrochloride', 1005.15);
insert into Products (Name, UnitCost) values ('Hydrogen Peroxide', 709.77);
insert into Products (Name, UnitCost) values ('Levothyroxine Sodium', 989.5);
insert into Products (Name, UnitCost) values ('Chelidonium majus, Echinacea angustifolia', 469.45);
insert into Products (Name, UnitCost) values ('ALUMINUM CHLOROHYDRATE', 22.48);
insert into Products (Name, UnitCost) values ('Tacrolimus', 579.87);
insert into Products (Name, UnitCost) values ('Lidocaine', 1005.26);
insert into Products (Name, UnitCost) values ('ANASTROZOLE', 351.56);
insert into Products (Name, UnitCost) values ('Dulcamara, Arnica montana, Rhus toxicodendron, Sanguinaria canadensis, Cartilago suis, Coenzyme A, Funiculus umbilicalis suis, Nadidum, Natrum oxalaceticum,', 1649.91);
insert into Products (Name, UnitCost) values ('Phenytoin Sodium', 938.65);
insert into Products (Name, UnitCost) values ('risperidone', 1533.57);
insert into Products (Name, UnitCost) values ('Lorazepam', 1249.84);
insert into Products (Name, UnitCost) values ('Dextromethorphan HBr, Guaifenesin', 1172.88);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 1735.38);
insert into Products (Name, UnitCost) values ('Cetirizine Hydrochloride', 324.2);
insert into Products (Name, UnitCost) values ('Acyclovir', 164.38);
insert into Products (Name, UnitCost) values ('House Dust', 643.52);
insert into Products (Name, UnitCost) values ('Ensulizole', 306.49);
insert into Products (Name, UnitCost) values ('Ibuprofen', 446.39);
insert into Products (Name, UnitCost) values ('Chlordiazepoxide Hydrochloride', 879.15);
insert into Products (Name, UnitCost) values ('Venlafaxine Hydrochloride', 326.33);
insert into Products (Name, UnitCost) values ('Omeprazole', 1126.23);
insert into Products (Name, UnitCost) values ('Levofloxacin', 1678.68);
insert into Products (Name, UnitCost) values ('Titanium Dioxide', 1893.64);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan HBr, Phenylephrine HCl, Doxylamine succinate', 780.75);
insert into Products (Name, UnitCost) values ('PETROLATUM', 1442.6);
insert into Products (Name, UnitCost) values ('Garlic', 83.79);
insert into Products (Name, UnitCost) values ('Diazepam', 1728.62);
insert into Products (Name, UnitCost) values ('Dextran 70, Glycerin, Hypromellose', 674.61);
insert into Products (Name, UnitCost) values ('Diphenhydramine citrate, Ibuprofen', 1308.01);
insert into Products (Name, UnitCost) values ('Acetaminophen, Phenylephrine HCl', 699.12);
insert into Products (Name, UnitCost) values ('Iron', 562.85);
insert into Products (Name, UnitCost) values ('Guanfacine Hydrochloride', 1941.91);
insert into Products (Name, UnitCost) values ('Naphazoline hydrochloride and Pheniramine Maleate', 237.38);
insert into Products (Name, UnitCost) values ('Lithium Carbonate', 1703.14);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octisalate, Octocrylene', 1726.78);
insert into Products (Name, UnitCost) values ('Amlodipine and Benazepril Hydrochloride', 1416.97);
insert into Products (Name, UnitCost) values ('Norethindrone Acetate/Ethinyl Estradiol', 754.92);
insert into Products (Name, UnitCost) values ('Rough Marsh Elder', 272.0);
insert into Products (Name, UnitCost) values ('Lithium Carbonate', 1798.6);
insert into Products (Name, UnitCost) values ('Lidocane', 1091.59);
insert into Products (Name, UnitCost) values ('TOPIRAMATE', 898.5);
insert into Products (Name, UnitCost) values ('Divalproex Sodium', 476.63);
insert into Products (Name, UnitCost) values ('Fluoride', 1200.52);
insert into Products (Name, UnitCost) values ('Trichoderma', 275.54);
insert into Products (Name, UnitCost) values ('Macadamia Nut', 1445.44);
insert into Products (Name, UnitCost) values ('Lisinopril', 818.6);
insert into Products (Name, UnitCost) values ('Heparin Sodium', 1949.82);
insert into Products (Name, UnitCost) values ('phenobarbital elixir', 43.19);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, and PHENYLEPHRINE HYDROCHLORIDE', 293.96);
insert into Products (Name, UnitCost) values ('Menthol', 309.84);
insert into Products (Name, UnitCost) values ('LISINOPRIL', 514.3);
insert into Products (Name, UnitCost) values ('Dextroamphetamine Sulfate', 526.0);
insert into Products (Name, UnitCost) values ('Topiramate', 239.62);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 1871.27);
insert into Products (Name, UnitCost) values ('lamotrigine', 1369.14);
insert into Products (Name, UnitCost) values ('LIDOCAINE HYDROCHLORIDE,EPINEPHRINE BITARTRATE', 1407.91);
insert into Products (Name, UnitCost) values ('Glipizide', 1166.82);
insert into Products (Name, UnitCost) values ('Parsnip', 1115.01);
insert into Products (Name, UnitCost) values ('Amphotericin B', 1495.61);
insert into Products (Name, UnitCost) values ('DIMETHICONE', 1537.25);
insert into Products (Name, UnitCost) values ('Triclosan', 636.93);
insert into Products (Name, UnitCost) values ('Triclocarban', 66.25);
insert into Products (Name, UnitCost) values ('Olanzapine', 329.13);
insert into Products (Name, UnitCost) values ('Titanium Dioxide', 900.7);
insert into Products (Name, UnitCost) values ('Betamethasone Dipropionate', 1641.9);
insert into Products (Name, UnitCost) values ('ENALAPRILAT', 1201.08);
insert into Products (Name, UnitCost) values ('Chlorpheniramine maleate and Pseudoephedrine hydrochloride and Dextromethorphan hydrobromide', 685.98);
insert into Products (Name, UnitCost) values ('Aluminum Chlorohydrate', 137.97);
insert into Products (Name, UnitCost) values ('Chondrus crispus, Fucus vesiculosus, Thyroidinum, Belladonna, Calcarea carbonica, Conium maculatum, Iodium, Kali carbonicum. Phosphorus, Pulsatilla, Silicea,', 1355.68);
insert into Products (Name, UnitCost) values ('Amoxicillin', 1281.17);
insert into Products (Name, UnitCost) values ('water', 1297.41);
insert into Products (Name, UnitCost) values ('Methyl Salicylate, Menthol, Camphor', 1484.89);
insert into Products (Name, UnitCost) values ('Glyburide-Metformin Hydrochloride', 1169.19);
insert into Products (Name, UnitCost) values ('Polyethylene Glycol 3350', 965.61);
insert into Products (Name, UnitCost) values ('Pantoprazole', 1526.4);
insert into Products (Name, UnitCost) values ('Sulfur', 54.01);
insert into Products (Name, UnitCost) values ('GLYCERIN', 1404.15);
insert into Products (Name, UnitCost) values ('Octinoxate, Octisalate', 1373.69);
insert into Products (Name, UnitCost) values ('Alprazolam', 1276.03);
insert into Products (Name, UnitCost) values ('Nicotine Polacrilex', 1984.89);
insert into Products (Name, UnitCost) values ('THYROID', 559.86);
insert into Products (Name, UnitCost) values ('ascorbic acid and chlolecalciferol and sodium fluorideand vitamin A plamitate', 128.05);
insert into Products (Name, UnitCost) values ('sodium ferric gluconate complex', 1467.53);
insert into Products (Name, UnitCost) values ('atovaquone and proguanil hydrochloride', 1451.33);
insert into Products (Name, UnitCost) values ('Hydralazine Hydrochloride', 199.58);
insert into Products (Name, UnitCost) values ('DIPHENHYDRAMINE HYDROCHLORIDE', 189.22);
insert into Products (Name, UnitCost) values ('metformin hydrochloride', 1656.12);
insert into Products (Name, UnitCost) values ('Sodium Fluoride and Potassium Nitrate', 630.04);
insert into Products (Name, UnitCost) values ('Benzalkonium chloride', 368.16);
insert into Products (Name, UnitCost) values ('Fluocinonide', 1247.14);
insert into Products (Name, UnitCost) values ('METHOCARBAMOL', 640.0);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 913.81);
insert into Products (Name, UnitCost) values ('fenoprofen calcium', 865.65);
insert into Products (Name, UnitCost) values ('Acetaminophen', 520.83);
insert into Products (Name, UnitCost) values ('Norethindrone and Ethinyl Estradiol Tablets', 675.91);
insert into Products (Name, UnitCost) values ('Norethindrone', 345.64);
insert into Products (Name, UnitCost) values ('Guaifenesin', 1672.71);
insert into Products (Name, UnitCost) values ('Clotrimazole', 1480.93);
insert into Products (Name, UnitCost) values ('Menthol', 446.01);
insert into Products (Name, UnitCost) values ('Lisinopril and Hydrochlorothiazide', 1421.18);
insert into Products (Name, UnitCost) values ('dorzolamide hydrochloride', 796.12);
insert into Products (Name, UnitCost) values ('METOPROLOL SUCCINATE', 207.38);
insert into Products (Name, UnitCost) values ('Quetiapine fumarate', 982.33);
insert into Products (Name, UnitCost) values ('Isopropyl Alcohol', 362.4);
insert into Products (Name, UnitCost) values ('methylphenidate hydrochloride', 410.35);
insert into Products (Name, UnitCost) values ('NAJA NAJA VENOM', 1511.19);
insert into Products (Name, UnitCost) values ('Oxygen', 1526.6);
insert into Products (Name, UnitCost) values ('Carbidopa and Levodopa', 152.07);
insert into Products (Name, UnitCost) values ('Diazepam', 147.6);
insert into Products (Name, UnitCost) values ('Famciclovir', 1374.56);
insert into Products (Name, UnitCost) values ('Chlorpheniramine maleate, Phenylephrine HCl', 1099.77);
insert into Products (Name, UnitCost) values ('Hydrocodone Bitartrate and Acetaminophen', 894.06);
insert into Products (Name, UnitCost) values ('Diphenhydramine HCl', 1624.23);
insert into Products (Name, UnitCost) values ('beclomethasone dipropionate', 1095.68);
insert into Products (Name, UnitCost) values ('Alcohol', 1339.66);
insert into Products (Name, UnitCost) values ('Polyethylen Glycol and Propylene Gloycol', 163.68);
insert into Products (Name, UnitCost) values ('OCTINOXATE', 736.44);
insert into Products (Name, UnitCost) values ('Levothyroxine Sodium', 200.21);
insert into Products (Name, UnitCost) values ('GLYCINE', 1803.87);
insert into Products (Name, UnitCost) values ('Duloxetine', 1457.01);
insert into Products (Name, UnitCost) values ('indomethacin', 1329.67);
insert into Products (Name, UnitCost) values ('Meclizine HCl', 617.13);
insert into Products (Name, UnitCost) values ('ARNICA MONTANA,COPPER,POTASSIUM PHOSPHATE, DIBASIC,LACTIC ACID, DL-,MAGNESIUM PHOSPHATE, DIBASIC TRIHYDRATE.', 283.01);
insert into Products (Name, UnitCost) values ('Octinoxate, Octisalate, Avobenzone, Octocrylene', 575.94);
insert into Products (Name, UnitCost) values ('Treatment Set TS329197', 1969.83);
insert into Products (Name, UnitCost) values ('PYRITHIONE ZINC', 730.52);
insert into Products (Name, UnitCost) values ('Naphazoline Hydrochloride and Hypromellose', 143.26);
insert into Products (Name, UnitCost) values ('hydroxyzine pamoate', 851.24);
insert into Products (Name, UnitCost) values ('Doxazosin Mesylate', 664.55);
insert into Products (Name, UnitCost) values ('Treatment Set TS129085', 1664.8);
insert into Products (Name, UnitCost) values ('Bacitracin Zinc, Polymyxin B Sulfate, Neomycin Sulfate, Pramoxine Hydrochloride', 124.0);
insert into Products (Name, UnitCost) values ('Hydrocortisone', 373.63);
insert into Products (Name, UnitCost) values ('Titanium Dioxide, Zinc Oxide, and Octinoxate', 1468.65);
insert into Products (Name, UnitCost) values ('DIMETHICONE', 259.37);
insert into Products (Name, UnitCost) values ('Hydrochlorothiazide', 283.86);
insert into Products (Name, UnitCost) values ('Saltbush', 254.99);
insert into Products (Name, UnitCost) values ('ALUMINUM CHLOROHYDRATE', 1354.38);
insert into Products (Name, UnitCost) values ('alcohol, fumaria officinalis flowering top, calcium sulfide, bos taurus lymph, sus scrofa lymph, pinus sylvestris leafy twig, green peppercorn, prunus spinosa flower bud, silicon dioxide, bos taurus spleen, sus scrofa spleen, sulfuric acid', 1112.01);
insert into Products (Name, UnitCost) values ('Saline Laxative', 1819.1);
insert into Products (Name, UnitCost) values ('hydroxyzine hydrochloride', 1917.81);
insert into Products (Name, UnitCost) values ('Alcohol', 835.93);
insert into Products (Name, UnitCost) values ('Cosyntropin', 1748.94);
insert into Products (Name, UnitCost) values ('Hydroquinone', 43.68);
insert into Products (Name, UnitCost) values ('Sanicula, Abrotanum, Argentum nitricum, Arsenicum album, Baryta carbonica, Borax, Bryonia, Cactus grandiflorus, Calcarea fluorica, Calcarea phosphorica, Calcarea sulphurica, Chelidonium majus, Cholesterinum, Coffea cruda, Conium maculatum, Dulcamara, Ferrum phosphoricum, Fumaria officinalis, Gratiola officinalis, Helleborus niger, Hepar sulphuris calcareum, Hydrastis canadensis, Hydrofluoricum acidum, Iodium, Kali carbonicum, Kali muriaticum, Kali phosphoricum, Kali sulphuricum, Lilium tigrinum', 455.55);
insert into Products (Name, UnitCost) values ('Menthol', 111.25);
insert into Products (Name, UnitCost) values ('ipratropium bromide and albuterol sulfate', 556.52);
insert into Products (Name, UnitCost) values ('Glycopyrrolate', 1834.64);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octisalate, and Octocrylene', 746.65);
insert into Products (Name, UnitCost) values ('Acetaminophen', 22.03);
insert into Products (Name, UnitCost) values ('Titanium Dioxide, Octinoxate/EthylhexylMehtoxycinnamate', 353.82);
insert into Products (Name, UnitCost) values ('OCTINOXATE and ZINC OXIDE', 564.76);
insert into Products (Name, UnitCost) values ('Meclizine Hydrochloride', 1630.49);
insert into Products (Name, UnitCost) values ('Acetaminophen', 96.98);
insert into Products (Name, UnitCost) values ('Alcohol', 120.73);
insert into Products (Name, UnitCost) values ('ALCOHOL', 1995.69);
insert into Products (Name, UnitCost) values ('ibuprofen', 419.98);
insert into Products (Name, UnitCost) values ('montelukast sodium', 857.29);
insert into Products (Name, UnitCost) values ('DONEPEZIL HYDROCHLORIDE', 1485.49);
insert into Products (Name, UnitCost) values ('propionibacterium acnes', 571.9);
insert into Products (Name, UnitCost) values ('Bupropion Hydrochloride', 610.79);
insert into Products (Name, UnitCost) values ('Ensulizole', 511.39);
insert into Products (Name, UnitCost) values ('Cilostazol', 1742.12);
insert into Products (Name, UnitCost) values ('Piperonyl butoxide, Pyrethrum extract', 969.41);
insert into Products (Name, UnitCost) values ('Potassium Chloride, Dextrose Monohydrate and Sodium Chloride', 1862.08);
insert into Products (Name, UnitCost) values ('Sodium Fluoride', 998.8);
insert into Products (Name, UnitCost) values ('thioridazine hydrochloride', 1491.84);
insert into Products (Name, UnitCost) values ('Zinc Oxide, Titanium Dioxide', 1372.34);
insert into Products (Name, UnitCost) values ('estradiol and norethindrone acetate', 572.31);
insert into Products (Name, UnitCost) values ('Naproxen Sodium', 340.94);
insert into Products (Name, UnitCost) values ('olmesartan medoxomil', 996.69);
insert into Products (Name, UnitCost) values ('DOCUSATE SODIUM', 553.71);
insert into Products (Name, UnitCost) values ('Ammonium Lactate', 96.81);
insert into Products (Name, UnitCost) values ('Nicotine Polacrilex', 1852.55);
insert into Products (Name, UnitCost) values ('Amiodarone Hydrochloride', 1880.41);
insert into Products (Name, UnitCost) values ('SIMETHICONE', 1972.71);
insert into Products (Name, UnitCost) values ('Longleaf Pine', 946.83);
insert into Products (Name, UnitCost) values ('Nadolol', 1893.89);
insert into Products (Name, UnitCost) values ('Sodium Fluoride', 170.69);
insert into Products (Name, UnitCost) values ('diclofenac sodium', 1652.51);
insert into Products (Name, UnitCost) values ('Amlodipine Besylate', 1292.03);
insert into Products (Name, UnitCost) values ('Octinoxate', 4.44);
insert into Products (Name, UnitCost) values ('Amlodipine Besylate', 1490.88);
insert into Products (Name, UnitCost) values ('ziprasidone hydrochloride', 1945.07);
insert into Products (Name, UnitCost) values ('Pyrithione Zinc', 1216.45);
insert into Products (Name, UnitCost) values ('Colloidal Oatmeal', 1283.49);
insert into Products (Name, UnitCost) values ('TRAZODONE HYDROCHLORIDE', 1475.91);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, and PHENYLEPHRINE HYDROCHLORIDE', 1959.88);
insert into Products (Name, UnitCost) values ('SODIUM MONOFLUOROPHOSPHATE', 1087.6);
insert into Products (Name, UnitCost) values ('Panthenol', 884.47);
insert into Products (Name, UnitCost) values ('lamotrigine', 968.63);
insert into Products (Name, UnitCost) values ('Metformin Hydrochloride', 1149.38);
insert into Products (Name, UnitCost) values ('lisinopril', 281.78);
insert into Products (Name, UnitCost) values ('Menthol', 1928.0);
insert into Products (Name, UnitCost) values ('ropinirole', 1158.42);
insert into Products (Name, UnitCost) values ('Menthol', 686.4);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine Succinate, Pseudoephedrine Hydrochloride', 842.07);
insert into Products (Name, UnitCost) values ('OCTINOXATE and TITANIUM DIOXIDE', 1621.69);
insert into Products (Name, UnitCost) values ('Octinoxate, Octisalate, Oxybenzone, Titanium Dioxide', 1335.75);
insert into Products (Name, UnitCost) values ('Cetirizine HCl', 1272.45);
insert into Products (Name, UnitCost) values ('Calcium carbonate', 1340.4);
insert into Products (Name, UnitCost) values ('oxygen', 1748.26);
insert into Products (Name, UnitCost) values ('Octinoxate', 78.81);
insert into Products (Name, UnitCost) values ('promethazine hydrochloride', 222.55);
insert into Products (Name, UnitCost) values ('fluocinonide', 1335.87);
insert into Products (Name, UnitCost) values ('MENTHOL', 948.8);
insert into Products (Name, UnitCost) values ('Lamotrigine', 1809.09);
insert into Products (Name, UnitCost) values ('Terbinafine', 1538.12);
insert into Products (Name, UnitCost) values ('Camphor, Menthol, Methyl Salicylate', 464.73);
insert into Products (Name, UnitCost) values ('Ailanthus', 959.3);
insert into Products (Name, UnitCost) values ('Granisetron Hydrochloride', 1874.39);
insert into Products (Name, UnitCost) values ('Yellow Dock', 482.45);
insert into Products (Name, UnitCost) values ('Fluoxetine Capsules', 1303.56);
insert into Products (Name, UnitCost) values ('Sertraline Hydrochloride', 1387.11);
insert into Products (Name, UnitCost) values ('Alumina 12X, Bryonia 4X, Colocynthis 4X, Lachesis mutus 30X, Lycopodium clavatum 4X, Mercurius corrosivus 8X, Nux vomica 6X, Plumbum aceticum 12X, Sulphur 12X', 519.73);
insert into Products (Name, UnitCost) values ('LISINOPRIL', 1420.35);
insert into Products (Name, UnitCost) values ('Silver, Giant Puffball, Colchicum Autumnale Bulb, Chamaelirium Luteum Root, Strychnos Ignatii Seed, Lactic Acid, DL-, Lycopodium Clavatum Spore, Phosphoric Acid, Phosphorus, Syzygium Cumini Seed, Uranyl Nitrate Hexahydrate', 601.44);
insert into Products (Name, UnitCost) values ('OCTINOXATE, TITANIUM DIOXIDE', 1696.93);
insert into Products (Name, UnitCost) values ('Norethindrone', 1130.19);
insert into Products (Name, UnitCost) values ('Citalopram', 1490.73);
insert into Products (Name, UnitCost) values ('MENTHOL', 1958.48);
insert into Products (Name, UnitCost) values ('Black Willow', 1563.12);
insert into Products (Name, UnitCost) values ('Prochlorperazine', 1038.86);
insert into Products (Name, UnitCost) values ('camphor (synthetic)', 610.78);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OCTISALATE, OCTOCRYLENE, TITANIUM DIOXIDE, and ZINC OXIDE', 1257.08);
insert into Products (Name, UnitCost) values ('Glycerin', 1030.03);
insert into Products (Name, UnitCost) values ('acetaminophen, dextromethorphan hbr, guaifenesin, phenylephrine hcl', 539.44);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 961.91);
insert into Products (Name, UnitCost) values ('Aspirin', 1311.76);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN', 301.83);
insert into Products (Name, UnitCost) values ('Doxorubicin Hydrochloride', 627.09);
insert into Products (Name, UnitCost) values ('Jack Pine Pollen', 1769.05);
insert into Products (Name, UnitCost) values ('Norethindrone', 327.36);
insert into Products (Name, UnitCost) values ('Diphenhydramine HCl', 121.52);
insert into Products (Name, UnitCost) values ('Octinoxate and Oxybenzone', 1067.28);
insert into Products (Name, UnitCost) values ('Valproic Acid', 465.73);
insert into Products (Name, UnitCost) values ('Terazosin hydrochloride', 1174.87);
insert into Products (Name, UnitCost) values ('Aconite, Arnica, Belladonna, Euphrasia, Gelsemium, Hypericum, Rhus Tox, Symphytum', 1988.97);
insert into Products (Name, UnitCost) values ('Loratadine and Pseudoephedrine Sulfate', 187.58);
insert into Products (Name, UnitCost) values ('Apocynum cannabinum, Baryta carbonica, Cactus grandiflorus, Convallaria majalis, Cypripedium pubescens, Gelsemium sempervirens, Glonoinum, Naja tripudians, Phosphorus, Spigelia anthelmia and Spongia tosta', 1188.96);
insert into Products (Name, UnitCost) values ('INTERLEUKIN-6', 518.38);
insert into Products (Name, UnitCost) values ('tetrabenazine', 738.02);
insert into Products (Name, UnitCost) values ('TRICLOSAN', 1565.1);
insert into Products (Name, UnitCost) values ('Aspirin', 1309.6);
insert into Products (Name, UnitCost) values ('triptorelin pamoate', 1014.28);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 695.85);
insert into Products (Name, UnitCost) values ('Amoxicillin', 407.5);
insert into Products (Name, UnitCost) values ('Promethazine Hydrochloride', 965.76);
insert into Products (Name, UnitCost) values ('oxymetazoline hydrochloride', 172.02);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 1324.27);
insert into Products (Name, UnitCost) values ('Sodium Bicarbonate', 734.76);
insert into Products (Name, UnitCost) values ('Mulberry Mix', 1069.56);
insert into Products (Name, UnitCost) values ('Loratadine, Pseudoephedrine', 948.1);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, OCTINOXATE', 1932.6);
insert into Products (Name, UnitCost) values ('Acarbose', 462.75);
insert into Products (Name, UnitCost) values ('Pyrithione Zinc', 1710.72);
insert into Products (Name, UnitCost) values ('Diclofenac Sodium', 1509.89);
insert into Products (Name, UnitCost) values ('Australian Pine', 1292.9);
insert into Products (Name, UnitCost) values ('Lovastatin', 379.11);
insert into Products (Name, UnitCost) values ('Cypress Arizona', 1614.63);
insert into Products (Name, UnitCost) values ('Hydrocortisone Valerate', 364.27);
insert into Products (Name, UnitCost) values ('TRAMADOL HYDROCHLORIDE AND ACETAMINOPHEN', 1184.88);
insert into Products (Name, UnitCost) values ('benzalkonium chloride', 1903.99);
insert into Products (Name, UnitCost) values ('Phendimetrazine Tartrate', 1168.5);
insert into Products (Name, UnitCost) values ('Hydrogen Peroxide', 1643.98);
insert into Products (Name, UnitCost) values ('Chlorhexidine Gluconate Solution', 1550.75);
insert into Products (Name, UnitCost) values ('Fexofenadine Hydrochloride', 1525.1);
insert into Products (Name, UnitCost) values ('ISOPROPYL ALCOHOL', 1211.55);
insert into Products (Name, UnitCost) values ('Amolodipine Besylate', 240.59);
insert into Products (Name, UnitCost) values ('pegaspargase', 299.34);
insert into Products (Name, UnitCost) values ('Oxymetazoline HCl', 423.82);
insert into Products (Name, UnitCost) values ('Terazosin Hydrochloride', 1763.08);
insert into Products (Name, UnitCost) values ('Semecarpus Anacardium Juice, Arnica Montana, Calcium Fluoride, Silybum Marianum Seed, Chincona Officinalis Bark, Herring Sperm DNA, Ginkgo, Egg Phospholipids, Achillea Millefolium, Phosphoric Acid, Saccharomyces Cerevisia RNA, Silicon Dioxide, and Zinc Sulphate Heptahydrate', 46.3);
insert into Products (Name, UnitCost) values ('Benzocaine', 495.05);
insert into Products (Name, UnitCost) values ('Carvedilol', 988.69);
insert into Products (Name, UnitCost) values ('Lisinopril', 1358.98);
insert into Products (Name, UnitCost) values ('oxymetazoline hydrochloride', 1364.71);
insert into Products (Name, UnitCost) values ('Benzoyl Peroxide', 28.75);
insert into Products (Name, UnitCost) values ('Ibuprofen', 460.51);
insert into Products (Name, UnitCost) values ('MENTHOL', 1983.02);
insert into Products (Name, UnitCost) values ('OCTINOXATE and TITANIUM DIOXIDE', 498.64);
insert into Products (Name, UnitCost) values ('Treatment Set TS329197', 1125.95);
insert into Products (Name, UnitCost) values ('Levonorgestrel and Ethinyl Estradiol', 912.4);
insert into Products (Name, UnitCost) values ('Antiseptic handwash', 306.98);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 20.01);
insert into Products (Name, UnitCost) values ('Hydroxyzine Hydrochloride', 60.23);
insert into Products (Name, UnitCost) values ('Milrinone Lactate', 1871.87);
insert into Products (Name, UnitCost) values ('Triclosan', 881.83);
insert into Products (Name, UnitCost) values ('AVOBENZONE, ENSULIZOLE, OCTICSALATE, OCTOCRYLENE', 329.65);
insert into Products (Name, UnitCost) values ('paroxetine hydrochloride hemihydrate', 930.46);
insert into Products (Name, UnitCost) values ('Promethazine Hydrochloride and Dextromethorphan Hydrobromide', 810.77);
insert into Products (Name, UnitCost) values ('Adenosine', 753.21);
insert into Products (Name, UnitCost) values ('AVOBENZONE, HOMOSALATE, OCTOCRYLENE, OXYBENZONE', 947.27);
insert into Products (Name, UnitCost) values ('metformin hydrochloride', 132.27);
insert into Products (Name, UnitCost) values ('Indocyanine green', 1956.25);
insert into Products (Name, UnitCost) values ('Ondansetron', 262.88);
insert into Products (Name, UnitCost) values ('Naproxen Sodium', 620.78);
insert into Products (Name, UnitCost) values ('AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE', 1733.78);
insert into Products (Name, UnitCost) values ('Warfarin Sodium', 925.46);
insert into Products (Name, UnitCost) values ('Allergenic Extracts Alum Precipitated', 1862.22);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 1357.15);
insert into Products (Name, UnitCost) values ('Prednisone', 984.22);
insert into Products (Name, UnitCost) values ('Clotrimazole', 1141.6);
insert into Products (Name, UnitCost) values ('Polyvinyl Alcohol', 1859.7);
insert into Products (Name, UnitCost) values ('nebivolol hydrochloride', 1303.3);
insert into Products (Name, UnitCost) values ('Ondansetron', 1139.39);
insert into Products (Name, UnitCost) values ('Losartan Potassium and Hydrochlorothiazide', 1030.32);
insert into Products (Name, UnitCost) values ('activated charcoal, ageratina aromatica root, ferrous iodide, gelsemium sempervirens root, calcium sulfide, histamine, interleukin-12 human, interferon gamma-1a, iodine, potassium gluconate, lycopodium clavatum spore, cajuput oil, black currant, rosa canina fruit, serotonin, xanthine, almond, apple, banana, barley, bean, beef, cashew, casein, emmental cultured, casein, lactococcus lactis cultured, casein, lactococcus lactis cultured aged, casein, lactococcus lactis cultured', 1016.33);
insert into Products (Name, UnitCost) values ('Witch Hazel', 1340.56);
insert into Products (Name, UnitCost) values ('ASPIRIN', 845.3);
insert into Products (Name, UnitCost) values ('Standardized Grass Pollen, Grass Mix 4', 127.19);
insert into Products (Name, UnitCost) values ('divalproex sodium', 597.18);
insert into Products (Name, UnitCost) values ('White Hickory', 109.91);
insert into Products (Name, UnitCost) values ('Treatment Set TS334946', 1317.98);
insert into Products (Name, UnitCost) values ('Magesium Citrate', 822.14);
insert into Products (Name, UnitCost) values ('ciprofloxacin hydrochloride', 1061.6);
insert into Products (Name, UnitCost) values ('rifapentine', 704.68);
insert into Products (Name, UnitCost) values ('epidermophyton floccosum', 1411.1);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1950.13);
insert into Products (Name, UnitCost) values ('Losartan Potassium', 107.01);
insert into Products (Name, UnitCost) values ('Pramipexole Dihydrochloride', 980.53);
insert into Products (Name, UnitCost) values ('Peach', 754.14);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 914.75);
insert into Products (Name, UnitCost) values ('Amiodarone Hydrochloride', 1955.57);
insert into Products (Name, UnitCost) values ('ETHYL ALCOHOL', 1138.13);
insert into Products (Name, UnitCost) values ('albuterol sulfate', 71.48);
insert into Products (Name, UnitCost) values ('Amiodarone Hydrochloride', 1525.04);
insert into Products (Name, UnitCost) values ('sertraline hydrochloride', 524.81);
insert into Products (Name, UnitCost) values ('potassium chloride', 1724.92);
insert into Products (Name, UnitCost) values ('Milk, Whole Cow', 269.49);
insert into Products (Name, UnitCost) values ('DOCUSATE SODIUM', 1983.24);
insert into Products (Name, UnitCost) values ('Cefazolin', 42.77);
insert into Products (Name, UnitCost) values ('Promethazine hydrochloride', 1976.34);
insert into Products (Name, UnitCost) values ('Furosemide', 1169.67);
insert into Products (Name, UnitCost) values ('palifermin', 1483.9);
insert into Products (Name, UnitCost) values ('tapentadol hydrochloride', 1005.79);
insert into Products (Name, UnitCost) values ('Azithromycin', 1412.12);
insert into Products (Name, UnitCost) values ('amlodipine besylate and atorvastatin calcium', 360.61);
insert into Products (Name, UnitCost) values ('amaranthus retroflexus pollen and amaranthus spinosus pollen', 1451.96);
insert into Products (Name, UnitCost) values ('CATTLE EPITHELIA', 1972.64);
insert into Products (Name, UnitCost) values ('Famotidine, Calcium Carbonate, Magnesium Hydroxide', 1178.05);
insert into Products (Name, UnitCost) values ('ACONITUM FEROX', 337.54);
insert into Products (Name, UnitCost) values ('CONIUM MACULATUM FLOWERING TOP', 1105.2);
insert into Products (Name, UnitCost) values ('Piperonyl Butoxide, Pyrethrum Extract', 746.81);
insert into Products (Name, UnitCost) values ('Clarithromycin', 856.27);
insert into Products (Name, UnitCost) values ('Amoxicillin', 24.88);
insert into Products (Name, UnitCost) values ('Ranitidine', 971.61);
insert into Products (Name, UnitCost) values ('Glipizide', 449.21);
insert into Products (Name, UnitCost) values ('clonidine hydrochloride', 1348.16);
insert into Products (Name, UnitCost) values ('Torsemide', 195.11);
insert into Products (Name, UnitCost) values ('ESCITALOPRAM OXALATE', 491.86);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex Gly', 133.18);
insert into Products (Name, UnitCost) values ('Loxapine Succinate', 1355.06);
insert into Products (Name, UnitCost) values ('SPIGELIA', 151.79);
insert into Products (Name, UnitCost) values ('Influenza Vaccine Live Intranasal', 781.96);
insert into Products (Name, UnitCost) values ('Phenylephrine hydrochloride', 1064.01);
insert into Products (Name, UnitCost) values ('albiglutide', 1361.6);
insert into Products (Name, UnitCost) values ('Ibuprofen', 1458.95);
insert into Products (Name, UnitCost) values ('Sulindac', 1672.84);
insert into Products (Name, UnitCost) values ('White petroleum', 463.82);
insert into Products (Name, UnitCost) values ('sodium chloride, sodium lactate, calcium chloride, magnesium chloride and dextrose', 524.85);
insert into Products (Name, UnitCost) values ('PREGABALIN', 385.45);
insert into Products (Name, UnitCost) values ('Causticum, Natrum muriaticum, Nus vomica, Pulsatilla, Sepia, Staphysagria, Thuja occidentalis,', 192.38);
insert into Products (Name, UnitCost) values ('CLINDAMYCIN PHOSPHATE', 1704.44);
insert into Products (Name, UnitCost) values ('Droperidol', 475.02);
insert into Products (Name, UnitCost) values ('Dextromethorphan Hydrobromide, Guaifenesin', 53.45);
insert into Products (Name, UnitCost) values ('Morphine Sulfate', 1471.32);
insert into Products (Name, UnitCost) values ('Adapalene', 1957.42);
insert into Products (Name, UnitCost) values ('lettuce', 92.06);
insert into Products (Name, UnitCost) values ('Bisacodyl', 53.82);
insert into Products (Name, UnitCost) values ('Vinorelbine', 559.95);
insert into Products (Name, UnitCost) values ('Benzalkonium Chloride', 1499.15);
insert into Products (Name, UnitCost) values ('camphor and menthol', 1463.12);
insert into Products (Name, UnitCost) values ('LORAZEPAM', 1079.78);
insert into Products (Name, UnitCost) values ('Nicotine Polacrilex', 987.94);
insert into Products (Name, UnitCost) values ('fibrinogen human and thrombin human', 251.67);
insert into Products (Name, UnitCost) values ('Lamotrigine', 1261.66);
insert into Products (Name, UnitCost) values ('Loperamide HCl', 1912.76);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 1233.06);
insert into Products (Name, UnitCost) values ('everolimus', 248.76);
insert into Products (Name, UnitCost) values ('Hydrocodone Bitartrate and Acetaminophen', 1569.37);
insert into Products (Name, UnitCost) values ('Drosera 1X, Mentholum 2X, Convallaria majalis 3X, Lobelia inflata 3X, Stramonium 6X, Aconitum napellus 3X, Ammi visnaga 2X, Kali iodatum 3X', 443.62);
insert into Products (Name, UnitCost) values ('sodium fluoride', 407.63);
insert into Products (Name, UnitCost) values ('Acetaminophen', 957.96);
insert into Products (Name, UnitCost) values ('Eptifibatide', 736.63);
insert into Products (Name, UnitCost) values ('Triclosan', 1556.73);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Pentachlorohydrex Gly', 1259.11);
insert into Products (Name, UnitCost) values ('METFORMIN HYDROCHLORIDE', 9.98);
insert into Products (Name, UnitCost) values ('Neurospora spp', 1436.02);
insert into Products (Name, UnitCost) values ('Argentum Veratrum', 651.83);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 1958.43);
insert into Products (Name, UnitCost) values ('Ampicillin and Sulbactam', 680.42);
insert into Products (Name, UnitCost) values ('Oxycodone Hydrochloride', 135.91);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN, PHENYLEPHRINE HYDROCHLORIDE', 614.14);
insert into Products (Name, UnitCost) values ('Povidone-iodine', 725.36);
insert into Products (Name, UnitCost) values ('SODIUM FLUORIDE', 377.15);
insert into Products (Name, UnitCost) values ('Nitrogen', 1227.67);
insert into Products (Name, UnitCost) values ('acetaminophen, dextromethorphan hydrobromide, doxylamine succinate', 952.07);
insert into Products (Name, UnitCost) values ('pravastatin sodium', 920.05);
insert into Products (Name, UnitCost) values ('Octinoxate, Titanium Dioxide', 794.62);
insert into Products (Name, UnitCost) values ('Avobenzone, Octinoxate, Octisalate, and Oxybenzone', 210.71);
insert into Products (Name, UnitCost) values ('Octinoxate and Oxybenzone', 1922.4);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 178.91);
insert into Products (Name, UnitCost) values ('PETROLATUM', 697.5);
insert into Products (Name, UnitCost) values ('Quartz 8', 571.0);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan HBr, and Phenylephrine HCL.', 1222.82);
insert into Products (Name, UnitCost) values ('naproxen sodium', 157.36);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 141.55);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', 1297.92);
insert into Products (Name, UnitCost) values ('Ranitidine', 512.69);
insert into Products (Name, UnitCost) values ('Actaea spicata, Aesculus hippocastanum, Arnica montana, Bellis perennis, Bryonia, Calcarea carbonica, Calcarea fluorica, Causticum, Cimicifuga racemosa, Formicum acidum, Hypericum perforatum, Ledum palustre, Lithium carbonicum, Magnesia phosphorica, Phytolacca decandra, Pulsatilla, Rhododendron chrysanthum, Rhus toxicodendron, Ruta graveolens, Salicylicum acidum, Sepia, Zincum metallicum', 311.96);
insert into Products (Name, UnitCost) values ('OCTINOXATE and ZINC OXIDE', 425.74);
insert into Products (Name, UnitCost) values ('Bismuth Subsalicylate', 685.72);
insert into Products (Name, UnitCost) values ('Menthol', 1931.69);
insert into Products (Name, UnitCost) values ('Nitrogen', 728.06);
insert into Products (Name, UnitCost) values ('ATORVASTATIN CALCIUM', 1927.5);
insert into Products (Name, UnitCost) values ('VERATRUM VIRIDE ROOT', 1407.39);
insert into Products (Name, UnitCost) values ('carfilzomib', 976.09);
insert into Products (Name, UnitCost) values ('Acetaminophen', 298.72);
insert into Products (Name, UnitCost) values ('Calcium Acetate', 75.59);
insert into Products (Name, UnitCost) values ('Ranitidine', 660.74);
insert into Products (Name, UnitCost) values ('NITROUS OXIDE', 904.3);
insert into Products (Name, UnitCost) values ('ATROPA BELLADONNA', 1709.66);
insert into Products (Name, UnitCost) values ('frovatriptan succinate', 1774.26);
insert into Products (Name, UnitCost) values ('Atenolol', 998.59);
insert into Products (Name, UnitCost) values ('OXYGEN', 1564.08);
insert into Products (Name, UnitCost) values ('Aluminum zirconium tetrachlorohydrex gly', 1079.25);
insert into Products (Name, UnitCost) values ('Rosuvastatin calcium', 946.24);
insert into Products (Name, UnitCost) values ('hydroxyzine hydrochloride', 998.38);
insert into Products (Name, UnitCost) values ('ESZOPICLONE', 352.99);
insert into Products (Name, UnitCost) values ('promethazine hydrochloride', 1832.07);
insert into Products (Name, UnitCost) values ('OXYGEN', 1101.17);
insert into Products (Name, UnitCost) values ('Chamomilla and Mercurius Solubilis and Sulphur', 78.12);
insert into Products (Name, UnitCost) values ('Octinoxate and Oxybenzone', 653.44);
insert into Products (Name, UnitCost) values ('Ibuprofen, Pseudoephedrine Hydrochloride', 1661.45);
insert into Products (Name, UnitCost) values ('Methyl Salicylate, Menthol, Camphor (Synthetic)', 839.79);
insert into Products (Name, UnitCost) values ('Anticoagulant Citrate Phosphate Dextrose Adenine', 1476.09);
insert into Products (Name, UnitCost) values ('Sesame', 1517.12);
insert into Products (Name, UnitCost) values ('ARNICA MONTANA - RHUS TOXICODENDRON - RUTA GRAVEOLENS', 1146.41);
insert into Products (Name, UnitCost) values ('NAPROXEN SODIUM', 1429.58);
insert into Products (Name, UnitCost) values ('Verapamil hydrochloride', 942.39);
insert into Products (Name, UnitCost) values ('carvedilol', 714.22);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine Succinate', 1897.14);
insert into Products (Name, UnitCost) values ('Zinc oxide', 1103.92);
insert into Products (Name, UnitCost) values ('Mandragora Rheum', 638.94);
insert into Products (Name, UnitCost) values ('STEMPHYLIUM SOLANI', 488.2);
insert into Products (Name, UnitCost) values ('Salicylic Acid', 1404.31);
insert into Products (Name, UnitCost) values ('Aspergillus repens', 1056.99);
insert into Products (Name, UnitCost) values ('NITROGEN', 1932.19);
insert into Products (Name, UnitCost) values ('Alprazolam', 1518.61);
insert into Products (Name, UnitCost) values ('Finasteride', 1837.53);
insert into Products (Name, UnitCost) values ('Hyoscyamine Sulfate Extended-Release', 281.17);
insert into Products (Name, UnitCost) values ('Antihemophilic Factor, Human Recombinant', 33.76);
insert into Products (Name, UnitCost) values ('Alcohol', 406.83);
insert into Products (Name, UnitCost) values ('VITAMIN A ACETATE, .BETA.-CAROTENE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, DL-, THIAMINE MONONITRATE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE HYDROCHLORIDE, FOLIC ACID, CYANOCOBALAMIN, CALCIUM CARBONATE, FERROUS FUMARATE, ZINC OXIDE, and CUPRIC OXIDE', 1657.1);
insert into Products (Name, UnitCost) values ('OXYGEN', 887.31);
insert into Products (Name, UnitCost) values ('Acebutolol Hydrochloride', 903.93);
insert into Products (Name, UnitCost) values ('rosiglitazone maleate and metformin hydrochloride', 1423.19);
insert into Products (Name, UnitCost) values ('Acetazolamide', 1886.34);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1001.99);
insert into Products (Name, UnitCost) values ('sertraline hydrochloride', 1967.68);
insert into Products (Name, UnitCost) values ('Risperidone', 1335.42);
insert into Products (Name, UnitCost) values ('Nizatidine', 1257.79);
insert into Products (Name, UnitCost) values ('Triclosan', 1037.87);
insert into Products (Name, UnitCost) values ('Salicylic acid', 427.87);
insert into Products (Name, UnitCost) values ('NITROUS OXIDE', 550.24);
insert into Products (Name, UnitCost) values ('Octinoxate and Avobenzone', 1311.82);
insert into Products (Name, UnitCost) values ('Naproxen', 1863.72);
insert into Products (Name, UnitCost) values ('Naproxen', 618.79);
insert into Products (Name, UnitCost) values ('Calc carb, Kreosotum, Lycopodium, Merc sol, Sepia', 290.47);
insert into Products (Name, UnitCost) values ('oxymorphone hydrochloride', 1196.39);
insert into Products (Name, UnitCost) values ('Citalopram', 1291.66);
insert into Products (Name, UnitCost) values ('Zinc Undecylenate Undecylenic acid', 495.25);
insert into Products (Name, UnitCost) values ('Metronidazole', 539.92);
insert into Products (Name, UnitCost) values ('Mirtazapine', 708.85);
insert into Products (Name, UnitCost) values ('Chlorpheniramine Maleate, Dextromethorphan Hydrobromide and Phenylephrine Hydrochloride', 1629.09);
insert into Products (Name, UnitCost) values ('Olanzapine', 612.06);
insert into Products (Name, UnitCost) values ('Isopropyl Alcohol', 865.46);
insert into Products (Name, UnitCost) values ('Venlafaxine Hydrochloride', 1811.13);
insert into Products (Name, UnitCost) values ('Diphenhydramine HCl', 1081.52);
insert into Products (Name, UnitCost) values ('SODIUM MONOFLUOROPHOSPHATE', 1923.67);
insert into Products (Name, UnitCost) values ('ESTROGENS, ESTERIFIED and METHYLTESTOSTERONE', 1293.21);
insert into Products (Name, UnitCost) values ('gemcitabine', 418.61);
insert into Products (Name, UnitCost) values ('OXYGEN', 952.62);
insert into Products (Name, UnitCost) values ('olmesartan medoxomil-hydrochlorothiazide', 1055.46);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 1144.76);
insert into Products (Name, UnitCost) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 1953.85);
insert into Products (Name, UnitCost) values ('CLADOSPORIUM SPHAEROSPERMUM', 1101.61);
insert into Products (Name, UnitCost) values ('Bay Leaf', 1862.71);
insert into Products (Name, UnitCost) values ('Cetirizine Hydrochloride', 1187.9);
insert into Products (Name, UnitCost) values ('Birch Mix', 905.99);
insert into Products (Name, UnitCost) values ('LYTTA VESICATORIA', 1817.04);
insert into Products (Name, UnitCost) values ('Cell Repair Aid', 1815.19);
insert into Products (Name, UnitCost) values ('Loratadine and Pseudoephedrine Sulfate', 1282.05);
insert into Products (Name, UnitCost) values ('Spearmint', 750.83);
insert into Products (Name, UnitCost) values ('Blackberry', 1127.59);
insert into Products (Name, UnitCost) values ('Mirtazapine', 1963.27);
insert into Products (Name, UnitCost) values ('Aletris farinosa, Apis mellifica, Arnica montana, Belladonna, Caulophyllum thalictroides, Chamomilla, Cimicifuga racemosa, Ferrum metallicum, Kali carbonicum, Sabina, Secale cornutum, Viburnum opulus', 1458.1);
insert into Products (Name, UnitCost) values ('BENZTROPINE MESYLATE', 610.03);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 1002.98);
insert into Products (Name, UnitCost) values ('Lidocaine Hydrochloride Anhydrous', 271.35);
insert into Products (Name, UnitCost) values ('Glipizide', 182.84);
insert into Products (Name, UnitCost) values ('Alprazolam', 767.99);
insert into Products (Name, UnitCost) values ('BENZALKONIUM CHLORIDE', 1620.33);
insert into Products (Name, UnitCost) values ('Octinoxate and Oxybenzone', 60.37);
insert into Products (Name, UnitCost) values ('Glycerin', 1554.3);
insert into Products (Name, UnitCost) values ('Prednisone', 449.17);
insert into Products (Name, UnitCost) values ('Agnus castus, Angelica sinensis radix, Apis mellifica, Aralia quinquefolia, Arnica montana, Cimicifuga racemosa, Galium aparine, Glycyrrhiza glabra, Oophorinum suis, Sepia, Thuja occidentalis, Viscum album,', 605.07);
insert into Products (Name, UnitCost) values ('Salicylic Acid', 341.47);
insert into Products (Name, UnitCost) values ('Pigweed Rough Redroot', 1127.12);
insert into Products (Name, UnitCost) values ('Oxygen', 238.5);
insert into Products (Name, UnitCost) values ('Trazodone Hydrochloride', 226.73);
insert into Products (Name, UnitCost) values ('Nifedipine', 1832.73);
insert into Products (Name, UnitCost) values ('acetaminophen', 1851.75);
insert into Products (Name, UnitCost) values ('Hydrogen Peroxide', 924.35);
insert into Products (Name, UnitCost) values ('Secale Quartz', 1089.02);
insert into Products (Name, UnitCost) values ('tramadol hydrochloride', 1567.31);
insert into Products (Name, UnitCost) values ('Oxymetazoline hydrochloride', 1550.91);
insert into Products (Name, UnitCost) values ('Viscum Mali e pl. tota 5%', 381.07);
insert into Products (Name, UnitCost) values ('Chloroxylenol', 721.7);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', 1608.73);
insert into Products (Name, UnitCost) values ('OCTINOXATE and OXYBENZONE', 920.62);
insert into Products (Name, UnitCost) values ('ARBUTIN', 1079.63);
insert into Products (Name, UnitCost) values ('omeprazole', 678.3);
insert into Products (Name, UnitCost) values ('HYDROXYZINE PAMOATE', 506.19);
insert into Products (Name, UnitCost) values ('Acetaminophen, Aspirin and caffeine', 1544.01);
insert into Products (Name, UnitCost) values ('Thompson Seedless Grape', 1715.66);
insert into Products (Name, UnitCost) values ('Oxygen', 647.97);
insert into Products (Name, UnitCost) values ('povidone-iodine and alcohol', 1101.76);
insert into Products (Name, UnitCost) values ('sodium fluoride', 1667.6);
insert into Products (Name, UnitCost) values ('dextromethorphan HBr, guaifenesin, phenylephrine HCl', 192.23);
insert into Products (Name, UnitCost) values ('ruxolitinib', 1490.67);
insert into Products (Name, UnitCost) values ('hydrochlorothiazide', 775.9);
insert into Products (Name, UnitCost) values ('Midazolam', 1810.44);
insert into Products (Name, UnitCost) values ('retapamulin', 710.04);
insert into Products (Name, UnitCost) values ('SODIUM FLUORIDE', 298.34);
insert into Products (Name, UnitCost) values ('BuPROPion Hydrochloride', 1342.07);
insert into Products (Name, UnitCost) values ('Hydrocortisone', 1413.57);
insert into Products (Name, UnitCost) values ('Diphenhydramine HCl', 738.98);
insert into Products (Name, UnitCost) values ('BENZOCAINE, RESORCINOL', 563.73);
insert into Products (Name, UnitCost) values ('OCTINOXATE', 465.4);
insert into Products (Name, UnitCost) values ('Galantamine', 1376.53);
insert into Products (Name, UnitCost) values ('ibuprofen', 898.08);
insert into Products (Name, UnitCost) values ('fluocinonide', 1286.08);
insert into Products (Name, UnitCost) values ('penciclovir', 258.46);
insert into Products (Name, UnitCost) values ('Octinoxate, Octisalate, and Titanium Dioxide', 1526.97);
insert into Products (Name, UnitCost) values ('ENALAPRIL MALEATE', 351.07);
insert into Products (Name, UnitCost) values ('Dextromethorphan HBr, Guaifenesin', 215.71);
insert into Products (Name, UnitCost) values ('Methyl Salicylate, Menthol and Capsaicin', 1254.21);
insert into Products (Name, UnitCost) values ('Benzalkonium Chloride', 174.68);
insert into Products (Name, UnitCost) values ('Influenzinum, Morbillinum, Pertussinum, Aconitum nap., Alumina, Antimon. tart., Arsenicum alb., Baptisia, Belladonna, Bryonia, Cinchona, Crotalus horridus, Gelsemium, Kali bic., Lachesis, Ledum, Merc. viv., Mezereum, Nux vom., Phosphorus, Pulsatilla, Rhus toxicodendron, Silicea, Sulphur, Thuja occ., Vaccinium, Apis mel., Echinacea, Hypericum', 882.59);
insert into Products (Name, UnitCost) values ('DONEPEZIL HYDROCHLORIDE', 1960.82);
insert into Products (Name, UnitCost) values ('Famotidine', 70.55);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, OCTINOXATE, OCTISALATE', 280.96);
insert into Products (Name, UnitCost) values ('POVIDONE-IODINE', 1627.82);
insert into Products (Name, UnitCost) values ('Perindopril Erbumine', 530.35);
insert into Products (Name, UnitCost) values ('Citalopram', 658.34);
insert into Products (Name, UnitCost) values ('fluorometholone', 883.84);
insert into Products (Name, UnitCost) values ('perphenazine', 1862.14);
insert into Products (Name, UnitCost) values ('sulfacetamide sodium', 1693.75);
insert into Products (Name, UnitCost) values ('Triclosan', 1500.29);
insert into Products (Name, UnitCost) values ('Prednisone', 707.92);
insert into Products (Name, UnitCost) values ('Pseudoephedrine Hydrochloride', 893.2);
insert into Products (Name, UnitCost) values ('Fluoxetine Hydrochloride', 1920.44);
insert into Products (Name, UnitCost) values ('CYCLOBENZAPRINE HYDROCHLORIDE', 1532.04);
insert into Products (Name, UnitCost) values ('Amoxicillin', 540.83);
insert into Products (Name, UnitCost) values ('warfarin sodium', 1909.78);
insert into Products (Name, UnitCost) values ('Nifedipine', 1823.23);
insert into Products (Name, UnitCost) values ('diazepam', 194.59);
insert into Products (Name, UnitCost) values ('topotecan hydrochloride', 430.08);
insert into Products (Name, UnitCost) values ('ENALAPRIL MALEATE', 1054.4);
insert into Products (Name, UnitCost) values ('Caffeine', 1139.8);
insert into Products (Name, UnitCost) values ('Hydrochlorothiazide', 1332.74);
insert into Products (Name, UnitCost) values ('influenza virus vaccine', 557.66);
insert into Products (Name, UnitCost) values ('Watercress', 1797.92);
insert into Products (Name, UnitCost) values ('SAMBUCUS NIGRA FLOWER ECHINACEA ANGUSTIFOLIA CALENDULA OFFICINALIS FLOWER PINE NEEDLE OIL (PINUS SYLVESTRIS) THUJA OCCIDENTALIS ROOT', 827.76);
insert into Products (Name, UnitCost) values ('Olanzapine', 287.08);
insert into Products (Name, UnitCost) values ('Cefadroxil', 1663.96);
insert into Products (Name, UnitCost) values ('Octinoxate, Zinc Oxide', 252.31);
insert into Products (Name, UnitCost) values ('Octinoxate and Titanium Dioxide', 1318.81);
insert into Products (Name, UnitCost) values ('Citalopram', 364.29);
insert into Products (Name, UnitCost) values ('Allspice', 1052.16);
insert into Products (Name, UnitCost) values ('House Dust Mite, Dermatophagoides farinae', 727.39);
insert into Products (Name, UnitCost) values ('Minocycline hydrochloride', 330.98);
insert into Products (Name, UnitCost) values ('Cetirizine HCl and Pseudoephedrine HCl', 1296.45);
insert into Products (Name, UnitCost) values ('Diltiazem Hydrochloride', 1222.5);
insert into Products (Name, UnitCost) values ('Menthol', 1569.36);
insert into Products (Name, UnitCost) values ('icatibant acetate', 1521.22);
insert into Products (Name, UnitCost) values ('Virginia Live Oak', 1607.46);
insert into Products (Name, UnitCost) values ('ropinirole hydrochloride', 1089.93);
insert into Products (Name, UnitCost) values ('clobetasol propionate', 1837.06);
insert into Products (Name, UnitCost) values ('Levisticum e rad. 3', 1657.92);
insert into Products (Name, UnitCost) values ('Polyvinyl Alcohol and Povidone and Tetrahydrozoline Hydrochloride', 1722.84);
insert into Products (Name, UnitCost) values ('UREA', 1808.41);
insert into Products (Name, UnitCost) values ('Triclosan', 524.57);
insert into Products (Name, UnitCost) values ('Triclosan', 526.43);
insert into Products (Name, UnitCost) values ('Clonazepam', 1774.06);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, PHENYLEPHRINE HYDROCHLORIDE', 1972.74);
insert into Products (Name, UnitCost) values ('Dexamethasone Sodium Phosphate, Lidocaine Hydrochloride, Maricaine, Povidine Iodine', 877.62);
insert into Products (Name, UnitCost) values ('Chloroxylenol', 1834.81);
insert into Products (Name, UnitCost) values ('Diazepam', 1247.08);
insert into Products (Name, UnitCost) values ('meclizine hydrochloride', 15.78);
insert into Products (Name, UnitCost) values ('Arsenicum iodatum, Bryonia, Cistus canadensis, Hepar sulph. calc., Histaminum hydrochloricum, Hydrastis, Iodium, Kali bic., Kali iod., Merc. iod. rub., Merc. viv., Nux vom., Phosphorus, Pulsatilla, Sabadilla, Sticta, Verbascum, Echinacea', 1745.18);
insert into Products (Name, UnitCost) values ('Triclosan', 598.11);
insert into Products (Name, UnitCost) values ('Anastrozole', 1732.35);
insert into Products (Name, UnitCost) values ('ARIPIPRAZOLE', 1553.07);
insert into Products (Name, UnitCost) values ('WITCH HAZEL', 859.85);
insert into Products (Name, UnitCost) values ('Eucalyptol', 1547.78);
insert into Products (Name, UnitCost) values ('HYOSCYAMINE SULFATE', 1730.61);
insert into Products (Name, UnitCost) values ('ANGELICA ARCHANGELICA ROOT SALVIA OFFICINALIS LEAF HYOSCYAMUS NIGER SILVER NITRATE', 1166.87);
insert into Products (Name, UnitCost) values ('quetiapine fumarate', 293.69);
insert into Products (Name, UnitCost) values ('Diphenhydramine Hydrochloride', 898.68);
insert into Products (Name, UnitCost) values ('risperidone', 1207.24);
insert into Products (Name, UnitCost) values ('Ponderosa Pine', 1794.28);
insert into Products (Name, UnitCost) values ('Digoxin', 359.62);
insert into Products (Name, UnitCost) values ('red bell pepper', 1785.29);
insert into Products (Name, UnitCost) values ('Arnica Stannum', 734.4);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Trichlorohydrex Gly', 799.21);
insert into Products (Name, UnitCost) values ('Propranolol Hydrochloride', 909.37);
insert into Products (Name, UnitCost) values ('hydrocortisone acetate and pramoxine hydrochloride', 1860.69);
insert into Products (Name, UnitCost) values ('CEFPROZIL', 923.93);
insert into Products (Name, UnitCost) values ('Doxycycline Hyclate', 126.08);
insert into Products (Name, UnitCost) values ('Glipizide', 236.68);
insert into Products (Name, UnitCost) values ('fluticasone propionate', 780.53);
insert into Products (Name, UnitCost) values ('Acetaminophen, Diphenhydramine Hydrochloride, and Phenylephrine Hydrochloride', 1435.97);
insert into Products (Name, UnitCost) values ('Meprobamate', 1124.91);
insert into Products (Name, UnitCost) values ('Losartan Potassium', 892.28);
insert into Products (Name, UnitCost) values ('Lovastatin', 802.54);
insert into Products (Name, UnitCost) values ('Hay Fever Remedy', 1545.58);
insert into Products (Name, UnitCost) values ('Metoclopramide Hydrochloride', 365.59);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1197.4);
insert into Products (Name, UnitCost) values ('Doxycycline', 152.82);
insert into Products (Name, UnitCost) values ('Ibuprofen', 338.52);
insert into Products (Name, UnitCost) values ('PETROLATUM', 1608.64);
insert into Products (Name, UnitCost) values ('AVOBENZONE, OCTINOXATE, OCTISALATE, OXYBENZONE', 1976.09);
insert into Products (Name, UnitCost) values ('Linden', 220.95);
insert into Products (Name, UnitCost) values ('Dimethicone, Zinc Oxide', 977.37);
insert into Products (Name, UnitCost) values ('isosorbide mononitrate', 333.22);
insert into Products (Name, UnitCost) values ('mucor racemosus', 685.72);
insert into Products (Name, UnitCost) values ('Miconazole nitrate', 83.17);
insert into Products (Name, UnitCost) values ('Starch, Corn and Zinc Oxide', 589.47);
insert into Products (Name, UnitCost) values ('Enalapril Maleate', 1641.77);
insert into Products (Name, UnitCost) values ('Tramadol Hydrochloride', 1520.1);
insert into Products (Name, UnitCost) values ('Povidone-Iodine', 578.56);
insert into Products (Name, UnitCost) values ('Benzocaine', 84.66);
insert into Products (Name, UnitCost) values ('spironolactone', 1616.91);
insert into Products (Name, UnitCost) values ('zinc oxide and octinoxate lotion', 574.4);
insert into Products (Name, UnitCost) values ('zolpidem tartrate', 1639.1);
insert into Products (Name, UnitCost) values ('SENNOSIDES', 1394.71);
insert into Products (Name, UnitCost) values ('Salicylic Acid', 281.18);
insert into Products (Name, UnitCost) values ('CEFTRIAXONE', 785.62);
insert into Products (Name, UnitCost) values ('Ergocalciferol', 208.54);
insert into Products (Name, UnitCost) values ('Fentanyl Citrate, Bupivacaine HCl', 1542.61);
insert into Products (Name, UnitCost) values ('GENTAMICIN', 1836.43);
insert into Products (Name, UnitCost) values ('Diclofenac Sodium and Misoprostol', 854.0);
insert into Products (Name, UnitCost) values ('topiramate', 1681.09);
insert into Products (Name, UnitCost) values ('Oxymetazoline HCl', 1113.34);
insert into Products (Name, UnitCost) values ('Arroyo Willow', 170.24);
insert into Products (Name, UnitCost) values ('ropinirole', 612.49);
insert into Products (Name, UnitCost) values ('Folic Acid', 734.08);
insert into Products (Name, UnitCost) values ('Diclofenac Sodium', 197.98);
insert into Products (Name, UnitCost) values ('Eucalyptol, Menthol, Methyl Salicylate, Thymol', 799.12);
insert into Products (Name, UnitCost) values ('Apis mellifica, Borax, Carduus marianus, Echinacea, Galium aparine, Hepar suis, HGH, Mercurius corrosivus,', 1710.48);
insert into Products (Name, UnitCost) values ('Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Dextrose', 1418.67);
insert into Products (Name, UnitCost) values ('Mineral Oil, White Petrolatum', 1619.07);
insert into Products (Name, UnitCost) values ('Fucus Vesiculosus, Lymph Node, Medula Ossis Suis, Thymus, Thyroidinum, Calcarea Muriatica, Iodium', 1707.12);
insert into Products (Name, UnitCost) values ('FENTANYL', 1828.23);
insert into Products (Name, UnitCost) values ('ETHYL ALCOHOL', 1689.13);
insert into Products (Name, UnitCost) values ('Thuja occidentalis', 1692.91);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1902.91);
insert into Products (Name, UnitCost) values ('BuPROPion Hydrochloride', 844.38);
insert into Products (Name, UnitCost) values ('Witch hazel', 1193.83);
insert into Products (Name, UnitCost) values ('sulconazole nitrate', 571.14);
insert into Products (Name, UnitCost) values ('Acetaminophen', 636.14);
insert into Products (Name, UnitCost) values ('Losartan Potassium', 1235.22);
insert into Products (Name, UnitCost) values ('Neomycin, Polymyxin B, and Pramoxine Hydrochloride', 1843.13);
insert into Products (Name, UnitCost) values ('Citalopram', 1112.73);
insert into Products (Name, UnitCost) values ('Sodium Chloride', 290.06);
insert into Products (Name, UnitCost) values ('Lidocaine', 1954.79);
insert into Products (Name, UnitCost) values ('benzocaine, tetracaine hydrochloride', 860.16);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 437.77);
insert into Products (Name, UnitCost) values ('Dimethicone', 1887.74);
insert into Products (Name, UnitCost) values ('Ensulizole Octinoxate', 1265.69);
insert into Products (Name, UnitCost) values ('ETHYL ALCOHOL', 1852.44);
insert into Products (Name, UnitCost) values ('Lidocaine Hydrochloride', 1813.82);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OXYBENZONE', 1077.24);
insert into Products (Name, UnitCost) values ('Risperidone', 579.97);
insert into Products (Name, UnitCost) values ('tiagabine hydrochloride', 836.19);
insert into Products (Name, UnitCost) values ('Simvastatin', 1471.61);
insert into Products (Name, UnitCost) values ('Cefdinir', 789.47);
insert into Products (Name, UnitCost) values ('Para Grass Pollen', 822.72);
insert into Products (Name, UnitCost) values ('Dextromethorphan HBr, Doxylamine succinate', 1687.86);
insert into Products (Name, UnitCost) values ('Calcarea Phosphorica, Carbo Vegetabilis, Chamomilla, Colocynthis, Lycopodium, Moschus, Natrum Muriaticum, Silicea, Thuja', 802.95);
insert into Products (Name, UnitCost) values ('TIGECYCLINE', 988.27);
insert into Products (Name, UnitCost) values ('Naproxen Sodium', 1238.11);
insert into Products (Name, UnitCost) values ('OCTINOXATE', 579.58);
insert into Products (Name, UnitCost) values ('nystatin', 1361.62);
insert into Products (Name, UnitCost) values ('Chrysosplenium Chamomilla', 38.36);
insert into Products (Name, UnitCost) values ('Divalproex Sodium', 603.27);
insert into Products (Name, UnitCost) values ('BENZETHONIUM CHLORIDE', 1704.83);
insert into Products (Name, UnitCost) values ('Potassium Chloride', 1081.21);
insert into Products (Name, UnitCost) values ('Acetic Acid in Aqueous Aluminum Acetate', 494.4);
insert into Products (Name, UnitCost) values ('Levonorgestrel and Ethinyl Estradiol', 745.08);
insert into Products (Name, UnitCost) values ('Divalproex Sodium', 1926.15);
insert into Products (Name, UnitCost) values ('Sucralfate', 492.39);
insert into Products (Name, UnitCost) values ('Ethyl Alcohol', 1952.63);
insert into Products (Name, UnitCost) values ('Isopropyl Alcohol', 642.59);
insert into Products (Name, UnitCost) values ('GLYCERIN', 1342.32);
insert into Products (Name, UnitCost) values ('Euphrasia Officinalis, Ginko Biloba, Hydrastis Canadensis, Taraxacum Officinale, Beta Carotene, Cyanocobalamin, Glutathione', 561.76);
insert into Products (Name, UnitCost) values ('VANCOMYCIN HYDROCHLORIDE', 943.4);
insert into Products (Name, UnitCost) values ('Amoxicillin and Clavulanate Potassium', 279.63);
insert into Products (Name, UnitCost) values ('ETHYL ALCOHOL', 1680.72);
insert into Products (Name, UnitCost) values ('Standardized Mite, Dermatophagoides pteronyssinus', 1764.06);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 1038.45);
insert into Products (Name, UnitCost) values ('Lamotrigine', 1734.86);
insert into Products (Name, UnitCost) values ('GLYCERIN', 749.72);
insert into Products (Name, UnitCost) values ('Aluminum Chlorohydrate', 1235.61);
insert into Products (Name, UnitCost) values ('Potassium Chloride', 1217.92);
insert into Products (Name, UnitCost) values ('Indomethacin', 177.97);
insert into Products (Name, UnitCost) values ('Hydrocodone Bitartrate And Acetaminophen', 1130.95);
insert into Products (Name, UnitCost) values ('Magnesium Citrate', 1048.85);
insert into Products (Name, UnitCost) values ('Cefazolin', 235.21);
insert into Products (Name, UnitCost) values ('fexofenadine', 1878.45);
insert into Products (Name, UnitCost) values ('Camphor', 1111.77);
insert into Products (Name, UnitCost) values ('risperidone', 1158.84);
insert into Products (Name, UnitCost) values ('Quetiapine fumarate', 266.79);
insert into Products (Name, UnitCost) values ('Antihemophilic Factor, Human Recombinant', 1807.47);
insert into Products (Name, UnitCost) values ('tazarotene', 334.88);
insert into Products (Name, UnitCost) values ('Pseudoephedrine hydrochloride', 859.78);
insert into Products (Name, UnitCost) values ('Triclosan', 448.98);
insert into Products (Name, UnitCost) values ('Triclosan', 1431.21);
insert into Products (Name, UnitCost) values ('Asclepias Vincetoxicum, Echinacea, Hypothlamus (Suis), Hepar Suis, Methylcobalamin, Renal (Suis), Gambogia', 897.58);
insert into Products (Name, UnitCost) values ('Mefenamic Acid', 1736.01);
insert into Products (Name, UnitCost) values ('Solanum lycopersicum 4', 976.25);
insert into Products (Name, UnitCost) values ('Titanium Dioxide and Zinc Oxide', 485.3);
insert into Products (Name, UnitCost) values ('Minoxidil', 52.5);
insert into Products (Name, UnitCost) values ('omega-3-acid ethyl esters', 386.79);
insert into Products (Name, UnitCost) values ('Calcipotriene', 254.86);
insert into Products (Name, UnitCost) values ('Minocycline Hydrochloride', 629.91);
insert into Products (Name, UnitCost) values ('Cetirizine Hydrochloride', 1196.76);
insert into Products (Name, UnitCost) values ('amlodipine besylate and atorvastatin calcium', 1724.61);
insert into Products (Name, UnitCost) values ('Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', 3.71);
insert into Products (Name, UnitCost) values ('Squash Zucchini', 409.46);
insert into Products (Name, UnitCost) values ('Avena sativa, Kali phosphoricum, Cactus grandiflorus, Daphne indica, Eucalyptol, Lobelia inflata, Mentholum, Ignatia amara, Nux vomica, Staphysagria, Tabacum, Benzinum, Naphtalinum,', 1455.11);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OXYBENZONE, OCTISALATE, TITANIUM DIOXIDE', 740.66);
insert into Products (Name, UnitCost) values ('meloxicam', 1216.62);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 216.25);
insert into Products (Name, UnitCost) values ('lorazepam', 335.45);
insert into Products (Name, UnitCost) values ('Quinine Sulfate', 1368.66);
insert into Products (Name, UnitCost) values ('Alcohol', 1594.76);
insert into Products (Name, UnitCost) values ('Lisinopril', 341.43);
insert into Products (Name, UnitCost) values ('Anti-Itch Continuous Spray', 1677.56);
insert into Products (Name, UnitCost) values ('ANGELICA SINENSIS ROOT - ARNICA MONTANA - ASIAN GINSENG - ECHINACEA ANGUSTIFOLIA - FOMITOPSIS PINICOLA FRUITING BODY - INTERFERON GAMMA-1B - PAEONIA OFFICINALIS ROOT - PORK LIVER - REISHI - SILYBUM MA', 1120.31);
insert into Products (Name, UnitCost) values ('LEVOTHYROXINE SODIUM', 1846.95);
insert into Products (Name, UnitCost) values ('Ibuprofen', 185.22);
insert into Products (Name, UnitCost) values ('Ethyl Alcohol', 93.4);
insert into Products (Name, UnitCost) values ('PYRITHIONE ZINC', 1022.97);
insert into Products (Name, UnitCost) values ('Famotidine', 943.07);
insert into Products (Name, UnitCost) values ('topiramate', 450.26);
insert into Products (Name, UnitCost) values ('levothyroxine sodium', 1341.85);
insert into Products (Name, UnitCost) values ('Metformin hydrochloride', 564.33);
insert into Products (Name, UnitCost) values ('Carvedilol', 245.94);
insert into Products (Name, UnitCost) values ('Valproic Acid', 1.84);
insert into Products (Name, UnitCost) values ('cyclopentolate hydrochloride and phenylephrine hydrochloride', 921.22);
insert into Products (Name, UnitCost) values ('Titanium Dioxide and Zinc Oxide', 299.26);
insert into Products (Name, UnitCost) values ('Felodipine', 1910.67);
insert into Products (Name, UnitCost) values ('Aspirin', 527.95);
insert into Products (Name, UnitCost) values ('Buspirone Hydrochloride', 1227.62);
insert into Products (Name, UnitCost) values ('Oxcarbazepine', 1031.37);
insert into Products (Name, UnitCost) values ('Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine Succinate', 1303.39);
insert into Products (Name, UnitCost) values ('Oregon Ash', 333.29);
insert into Products (Name, UnitCost) values ('Ketotifen Fumarate', 103.74);
insert into Products (Name, UnitCost) values ('Cultivated Rye', 972.22);
insert into Products (Name, UnitCost) values ('Treatment Set TS330317', 1317.97);
insert into Products (Name, UnitCost) values ('isosorbide dinitrate', 347.8);
insert into Products (Name, UnitCost) values ('Metformin Hydrochloride', 43.28);
insert into Products (Name, UnitCost) values ('lisdexamfetamine dimesylate', 304.57);
insert into Products (Name, UnitCost) values ('Warfarin Sodium', 1214.97);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1220.84);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 480.41);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1830.83);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octinoxate, Octisalate, Oxybenzone', 1596.92);
insert into Products (Name, UnitCost) values ('rimabotulinumtoxinB', 417.14);
insert into Products (Name, UnitCost) values ('Nicotine polacrilex', 1571.12);
insert into Products (Name, UnitCost) values ('Insulin human', 1050.16);
insert into Products (Name, UnitCost) values ('Ropinirole', 1625.46);
insert into Products (Name, UnitCost) values ('Triclosan', 1651.35);
insert into Products (Name, UnitCost) values ('Mineral Oil', 340.02);
insert into Products (Name, UnitCost) values ('MINOXIDIL', 464.63);
insert into Products (Name, UnitCost) values ('ACARBOSE', 1733.07);
insert into Products (Name, UnitCost) values ('MENTHOL', 1600.11);
insert into Products (Name, UnitCost) values ('FORMALDEHYDE', 929.7);
insert into Products (Name, UnitCost) values ('ADENOSINE', 273.19);
insert into Products (Name, UnitCost) values ('DIPHENHYDRAMINE HYDROCHLORIDE AND ZINC ACETATE', 899.88);
insert into Products (Name, UnitCost) values ('Nux vomica', 541.64);
insert into Products (Name, UnitCost) values ('Ibuprofen', 1239.07);
insert into Products (Name, UnitCost) values ('Octinoxate and Oxybenzone', 433.49);
insert into Products (Name, UnitCost) values ('Anticoagulant Citrate Dextrose Solution Formula A', 443.23);
insert into Products (Name, UnitCost) values ('tizanidine hydrochloride', 427.39);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OXYBENZONE, TITANIUM DIOXIDE', 684.44);
insert into Products (Name, UnitCost) values ('Gemfibrozil', 936.35);
insert into Products (Name, UnitCost) values ('Benzoyl Peroxide', 903.99);
insert into Products (Name, UnitCost) values ('Lisinopril and Hydrochlorothiazide', 1228.67);
insert into Products (Name, UnitCost) values ('OCTINOXATE and TITANIUM DIOXIDE', 1454.87);
insert into Products (Name, UnitCost) values ('Calamine Plus No Touch Spray', 584.81);
insert into Products (Name, UnitCost) values ('Haloperidol', 1869.18);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, OCTINOXATE, OCTISALATE', 1172.25);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OXYBENZONE', 1733.91);
insert into Products (Name, UnitCost) values ('KETOROLAC TROMETHAMINE', 880.49);
insert into Products (Name, UnitCost) values ('METHYLPHENIDATE HYDROCHLORIDE', 992.18);
insert into Products (Name, UnitCost) values ('OCTINOXATE', 1540.18);
insert into Products (Name, UnitCost) values ('ATORVASTATIN CALCIUM', 1934.97);
insert into Products (Name, UnitCost) values ('Amino acids, Apis mellifica, Arnica montana, Fucus vesiculsus, Gambogia, Hepar suis, Phosphoricum acidum,', 282.95);
insert into Products (Name, UnitCost) values ('naproxen sodium', 1067.99);
insert into Products (Name, UnitCost) values ('Glimepiride', 849.63);
insert into Products (Name, UnitCost) values ('Donepezil Hydrochloride', 1518.75);
insert into Products (Name, UnitCost) values ('Sardine', 1009.28);
insert into Products (Name, UnitCost) values ('Captopril', 1585.23);
insert into Products (Name, UnitCost) values ('omeprazole, sodium bicarbonate', 293.34);
insert into Products (Name, UnitCost) values ('Lidocaine', 620.57);
insert into Products (Name, UnitCost) values ('TRICLOSAN', 457.11);
insert into Products (Name, UnitCost) values ('Glimepiride', 1387.28);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 1660.51);
insert into Products (Name, UnitCost) values ('Phenol', 1517.57);
insert into Products (Name, UnitCost) values ('Alcohol', 1195.05);
insert into Products (Name, UnitCost) values ('Potato, White Solanum tuberosum', 1437.97);
insert into Products (Name, UnitCost) values ('Diclofenac Sodium', 1363.74);
insert into Products (Name, UnitCost) values ('Doxycycline tablets and Benoxyl-CR Advanced Acne Wash', 1809.2);
insert into Products (Name, UnitCost) values ('Acetaminophen', 543.47);
insert into Products (Name, UnitCost) values ('Arsenicum 30c, Bryonia 30c, Carbo Animalis 30c, Caulophyllum 30c, Causticum 30c, Cocculus 30c, Colchicum 30c, Guaiacum 30c, Ledum 30c, Lycopodium 30c, Petroleum 30c, Rhus Tox 30c, Sepia 30c, Silicea 30c, Sulphur', 835.95);
insert into Products (Name, UnitCost) values ('guaifenesin dextromethorphan HBr', 1674.94);
insert into Products (Name, UnitCost) values ('CYPROHEPTADINE', 1996.3);
insert into Products (Name, UnitCost) values ('SALICYLIC ACID', 1562.88);
insert into Products (Name, UnitCost) values ('Proparacaine Hydrochloride', 1464.76);
insert into Products (Name, UnitCost) values ('PAMIDRONATE DISODIUM', 69.81);
insert into Products (Name, UnitCost) values ('Meperidine Hydrochloride', 972.59);
insert into Products (Name, UnitCost) values ('Dog Epithelium', 1688.03);
insert into Products (Name, UnitCost) values ('OCTINOXATE, OXYBENZONE', 526.65);
insert into Products (Name, UnitCost) values ('Eptifibatide', 910.1);
insert into Products (Name, UnitCost) values ('Sulfasalazine', 594.99);
insert into Products (Name, UnitCost) values ('Titanium Dioxide', 1317.52);
insert into Products (Name, UnitCost) values ('Ciprofloxacin', 951.6);
insert into Products (Name, UnitCost) values ('Acremonium Cephalosporium', 1709.98);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE', 1748.16);
insert into Products (Name, UnitCost) values ('MIDAZOLAM HYDROCHLORIDE', 948.91);
insert into Products (Name, UnitCost) values ('topiramate', 204.92);
insert into Products (Name, UnitCost) values ('Dextrose', 904.19);
insert into Products (Name, UnitCost) values ('Aletris, Apocynum, Cinchona, Cinnamomum, Conium, Helonias dioica, Lilium, Millefolium, Phosphorus, Secale, Thlaspi, Trillium pendulum, Apis mel., Hamamelis, Hydrastis', 247.35);
insert into Products (Name, UnitCost) values ('ALCOHOL', 282.79);
insert into Products (Name, UnitCost) values ('Titanium Dioxide', 150.07);
insert into Products (Name, UnitCost) values ('Famotidine', 40.44);
insert into Products (Name, UnitCost) values ('CAFFEINE - CHELIDONIUM MAJUS - DIEFFENBACHIA SEGUINE - JUNIPER - MATRICARIA RECUTITA - NICOTINE - PAPAVER RHOEAS FLOWER - PLANTAGO MAJOR - SCROPHULARIA NODOSA - SODIUM CHLORIDE - STRYCHNOS NUX-VOMICA', 1016.71);
insert into Products (Name, UnitCost) values ('Ailanthus', 658.22);
insert into Products (Name, UnitCost) values ('quinapril', 1974.74);
insert into Products (Name, UnitCost) values ('avobenzone, homosalate, octisalate, oxybenzone', 990.21);
insert into Products (Name, UnitCost) values ('OCTINOXATE, TITANIUM DIOXIDE, ZINC OXIDE, OCTISALATE', 1071.66);
insert into Products (Name, UnitCost) values ('Donepezil Hydrochloride', 501.38);
insert into Products (Name, UnitCost) values ('TITANIUM DIOXIDE, ZINC OXIDE', 1752.67);
insert into Products (Name, UnitCost) values ('Avobenzone, Octisalate and Octocrylene', 1317.54);
insert into Products (Name, UnitCost) values ('imipenem and cilastatin sodium', 164.11);
insert into Products (Name, UnitCost) values ('albuterol sulfate', 111.51);
insert into Products (Name, UnitCost) values ('Octinoxate', 1446.88);
insert into Products (Name, UnitCost) values ('Acarbose', 1775.59);
insert into Products (Name, UnitCost) values ('Dextromethorphan Hydrobromide', 804.73);
insert into Products (Name, UnitCost) values ('ropinirole', 1862.03);
insert into Products (Name, UnitCost) values ('simvastatin', 1668.29);
insert into Products (Name, UnitCost) values ('spironolactone', 96.2);
insert into Products (Name, UnitCost) values ('Nicotine Polacrilex', 486.65);
insert into Products (Name, UnitCost) values ('Diclofenac Sodium', 1276.6);
insert into Products (Name, UnitCost) values ('Glipizide', 432.85);
insert into Products (Name, UnitCost) values ('ALCOHOL', 359.77);
insert into Products (Name, UnitCost) values ('Red Oak', 139.11);
insert into Products (Name, UnitCost) values ('Potassium Chloride', 842.97);
insert into Products (Name, UnitCost) values ('Chlorhexidine Gluconate', 1473.97);
insert into Products (Name, UnitCost) values ('halobetasol propionate', 66.7);
insert into Products (Name, UnitCost) values ('Diltiazem Hydrochloride', 1607.01);
insert into Products (Name, UnitCost) values ('Triclosan', 1218.94);
insert into Products (Name, UnitCost) values ('CINCHONA OFFICINALIS BARK', 1790.28);
insert into Products (Name, UnitCost) values ('Hydrocodone Bitartrate and Acetaminophen', 1406.42);
insert into Products (Name, UnitCost) values ('Glycerin', 947.91);
insert into Products (Name, UnitCost) values ('Fluconazole', 1566.25);
insert into Products (Name, UnitCost) values ('Octinoxate and Titanium Dioxide', 189.83);
insert into Products (Name, UnitCost) values ('ANTIPYRINE AND BENZOCAINE', 1371.37);
insert into Products (Name, UnitCost) values ('Treatment Set TS330156', 1956.21);
insert into Products (Name, UnitCost) values ('ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, DEXTROMETHORPHAN HYDROBROMIDE, and PHENYLEPHRINE HYDROCHLORIDE', 1012.12);
insert into Products (Name, UnitCost) values ('Amoxicillin', 1925.8);
insert into Products (Name, UnitCost) values ('Octinoxate, Oxybenzone, Avobenzene, Octocrylene', 1922.1);
insert into Products (Name, UnitCost) values ('peginterferon alfa-2b', 969.3);
insert into Products (Name, UnitCost) values ('Ceftriaxone Sodium', 1162.85);
insert into Products (Name, UnitCost) values ('ropinirole', 1184.2);
insert into Products (Name, UnitCost) values ('Docusate calcium', 1728.44);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Trichlorohydrex Gly', 1668.8);
insert into Products (Name, UnitCost) values ('Atenolol', 229.4);
insert into Products (Name, UnitCost) values ('TRICLOSAN', 677.53);
insert into Products (Name, UnitCost) values ('Homosalate, Octinoxate, Octisalate, Oxybenzone, and Titanium Dioxide', 895.34);
insert into Products (Name, UnitCost) values ('Aluminum Zirconium Octachlorohydrex Gly', 110.61);
insert into Products (Name, UnitCost) values ('Glipizide', 870.68);
insert into Products (Name, UnitCost) values ('Octinoxate, Octisalate, Oxybenzone, Titanium Dioxide', 1189.28);
insert into Products (Name, UnitCost) values ('Dextromethorphan Hydrobromide, Doxylamine Succinate', 87.08);
insert into Products (Name, UnitCost) values ('ESCITALOPRAM OXALATE', 1459.42);
insert into Products (Name, UnitCost) values ('Olanzapine', 291.33);
insert into Products (Name, UnitCost) values ('Avobenzone, Homosalate, Octislate, Oxybenzone', 359.86);
insert into Products (Name, UnitCost) values ('Acetaminophen', 1347.42);
insert into Products (Name, UnitCost) values ('Hydroxyzine Pamoate', 44.59);
insert into Products (Name, UnitCost) values ('Standardized Grass Pollen, Timothy', 1379.45);
insert into Products (Name, UnitCost) values ('Aspirin', 1326.15);
insert into Products (Name, UnitCost) values ('Menthol', 1642.19);
insert into Products (Name, UnitCost) values ('CIPROFLOXACIN', 1536.05);
insert into Products (Name, UnitCost) values ('BRYONIA ALBA ROOT', 53.02);
insert into Products (Name, UnitCost) values ('captopril and hydrochlorothiazide', 143.28);
insert into Products (Name, UnitCost) values ('escitalopram', 418.73);
insert into Products (Name, UnitCost) values ('AVOBENZONE HOMOSALATE OCTISALATE OCTOCRYLENE OXYBENZONE', 1644.3);
insert into Products (Name, UnitCost) values ('Witch Hazel', 1672.79);
insert into Products (Name, UnitCost) values ('Trospium Chloride', 95.04);
insert into Products (Name, UnitCost) values ('glycerin', 1887.94);
insert into Products (Name, UnitCost) values ('Salicylic Acid', 908.93);
